index.html
lib/index.js
lib/styles.scss

card #1 
- Adds a basic search form to the root page.
- Adds header for search form.
- Adds basic reset styles to confirm that the CSS is properly linked.
- Index.html
- This was the completion of card 1. The search action will be a different card.
Closes #1

Creates Search Form #1

---

.gitignore
index.html
lib/index.js
package-lock.json
package.json
webpack.config.js

Closes #2 
- Adds an event listener to the search button
- Adds a Search Results list to the page
- Adds AJAX request to hit the Musixmatch API 
- Adds dotenv-webpack package for environment variables (API key)
- Adds API results to page in list format
- Driver-navigatored this with Bradley and Lance

Hit MusixMatch API to retrieve Search Results #2

---

index.html
lib/index.js
lib/styles.scss

closes #9
Adds styling to HTML/CSS for search results to display in a user friendly way. Additionally, adds function to JS file to clear previous results to ensure readability for user. Also adds searchReset to search that resets search field to empty and refocuses cursor for user.
The styling and addition to the DOMstrings is really all that is needed to be checked out to understand most of the PR. The main functional changes are the addition of a JS function that is called on search click setting all innerHTML to empty strings per search.

Add search result and style#9

---

index.html
lib/index.js

Closes #5 
- Adds self-calling function to index.js that uses `fetch` to get the list of favorites from the BE API
- Adds `postFavorites` method to post the favorites to the page
- Styling will be a separate card, this is just to get the information on the page

Call GET favorites to display favorites on page#5

---

index.html
lib/styles.scss

Closes #14 
- Adds Fira Sans Google Font
- Updates how divs are distributed on page to use flexbox for flexible styling
- Adds basic linear gradient background
- Consolidates styling for Search Results and Favorites into `box` class. When we add a Playlists box this will change things slightly if we are going per Bradley's wireframes, but the only thing would be that Favorites and Playlists would have different heights from Search Results. 
- Definitely flexible when it comes to styling - happy to go another direction with colors. Let me know if you'd rather try something else!

Style Favorites Display on Page#14

---

lib/index.js

Closes #4 
Adds the ability for a user to click on a song to favorite it then. It will be added to their favorites.
There is a rather complicated method to grab the HTML element dynamically so that the index can be referenced to the object array. That is located at the beginning of the event listener when they click on a favorite icon.

Post sent for add favorite

---

lib/index.js

closes #17 
Adds a function that tells the UI to append the favorites list. Then this function is called by the fetch request to post a new favorite
All new functionality is put down at the bottom of the fetch request that makes a new post

UI shows favorite as being a favorite as soon as you click it.

---

lib/index.js

Reverts asmolentzov/play_fe#21
Accidental merge done by errant dbl click.

Revert "UI shows favorite as being a favorite as soon as you click it."

---

lib/index.js

closes#17
Adds the functionality for a user to click on a favorite song and see it immediately added to their favorites.
All of the functionality is based around the function that is right below the add favorites event listener .

Adding favorite adds it to favorites column #17

---

lib/index.js
lib/styles.scss

Closes #18  
- Adds a Remove button to each favorite in the Favorites box, and adds basic styling
- Adds event listener to Favorites box
- Adds function to make a DELETE call to the BE API when the Remove button is clicked

Favorite is deleted when user clicks Remove #18

---

index.html
lib/index.js
lib/styles.scss

closes #26 
-The UI now displays all created playlists within a box when the page is loaded.
-Does not display songs associated with a playlist and as of now is not a link to a individual playlist. This functionality will be added at a later date.
-The function that calls the fetch request is located in the index.js file.

Playlists are displayed on page using get api/v1/playlists

---

lib/index.js
lib/styles.scss

Closes #6 
- Adds button to both `appendFavorites` and `postFavorites` functions for Add to Playlist
- Adds basic styling to button

Favorites can be Added to playlist - button is added to favorites

---

package-lock.json
package.json

Adds Express

---

index.html
lib/index.js

closes #34 
Shows the songs for each playlist on the DOM.

Adds songs showing under associated playlists

---

index.html
lib/index.js
lib/styles.scss

Closes #40 
-Adds accordion for the playlists list. 
-Basic styling for accordion
-New event listener set up to delegate down into playlist items

Add accordion to playlists#40

---

index.html
lib/index.js
lib/styles.scss

IMPORTANT MERGE CARD #40 FIRST
closes #38
-Adds check to ensure only one playlist can be active at a time.
-Adds check to ensure song can only be added to a playlist if it is active.
-Adds ability for user to see a song go to the playlist area of the DOM and be listed in those songs.
-Adds cleaner method for extracting relevant HTML to make a favorite songs html.
-Good place to begin would be to see the changes done to the accordion class.

Display selected favorite song under playlist

---

index.html
lib/index.js
lib/styles.scss

MERGE PRs for cards #40 then #38 then this PR.
closes #7 
-Adds working POST for a song being added to the select
-Fix songHtml in append favorites
-The new post method is called at the bottom of the append playlists method.

Post sent to update db with new song#7

---

lib/index.js
main.bundle.js

Closes #36 
- Adds sorting functionality to playlists so that they are sorted by average song rating when they load on the page

Rank Playlists By Average Song Ratings #36

---

index.html

closes #35 
-Adds search field and button to DOM to add new playlists
-It is wrapped in its own div in the index.html
-THERE IS NO CSS ON THIS CLASS CURRENTLY
-index.html and also boot server locally to see position

Adds button and field for new playlists to be added.

---

index.html
lib/index.js

MERGE #48 FIRST
closes #49
-Adds a event listener that calls the POST method to api/v1/playlists to create new playlist
-Adds remove button to playlists

Add playlist post and display#49

---

index.html
lib/index.js

closes #50 closes #51
-Adds Update button and field above the Playlist display area
-Adds Fetch call to PUT on clicking the update button if there is an active playlist and the field is not empty

Add update form and button#50

---

lib/index.js
main.bundle.js
package-lock.json
package.json

Closes #46 
- Adds BASE_URL environment variable instead of hardcoding localhost
- Updates heroku-postbuild script to include -p tag

Adds BASE_URL environment variable and updates script for heroku start

---

lib/index.js

closes #52
-Adds to the existing event listener on the playlistList to call the DELETE fetch call on a playlist when the remove button is pressed

DELETE is called on Playlist when button to remove is pressed

---

lib/index.js
main.bundle.js

- Hardcodes production BE URL instead of trying to use environment variable

Hardcodes production BE URL

---

lib/index.js

closes #59 closes #60
-Fixes Delete Bug
- Makes it so there is a fetch call after creation of a new playlist to regrab the playlists so that a user can delete a playlist right after it was created.

Fixes bug with delete button bug also make allow user to delete playlist after creation

---

main.bundle.js

Runs npm build to update production

Runs npm build

---

package-lock.json
package.json

- Updates npm packages per GitHub security alert suggestions - ran `npm update`
- Ran `npm start` to test locally and clicking through indicates that things are still working fine

Updates npm packages
